<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Contains Dependent Items (with Containers and Groups) model and the ordering algorithm.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="25.0.1" />
  </ItemGroup>
</Project>